version: '3'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: "2g"
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm install && npm run test"
    user: "1000:1000" 